#ifndef _DISTANCE_TRANSFORMATION_H_
#define _DISTANCE_TRANSFORMATION_H_

#include <math.h>
#include <float.h>
#include <string.h>

#include "omp.h"

typedef unsigned char uchar;

/*
	This function takes FT (Closet Feature Voxel Transformation) as an input and performs 
	distance tranformation based on the scheme.

	Supported schemes: center-to-center, center-to-face.

	Arguments: scheme - center-to-center or center-to-face;
		row_vol - The raw volume that contains the boundary face information;
		sp2 - Squared spacings
		height, width, depth - Size of the volume;
		ed_out - (1) contians FT generated by Maurer; (2) Final distance mapping output
*/
void distTransformation(char *scheme,
                        uchar *raw_vol,
		        float *sp2,	
                        int height, int width, int depth, 
                        double *ed_out);

/*
	Helper functions, the following functions are the building blocks of distTransformation
*/

/*
	distToClosetFacePointOfCFV: for each voxel with coordinate of (i, j, k), it determines
	the distance to the closet boundary face of its CFV (closet feature voxel) with coordinate of 
	(cfv_i, cfv_j, cfv_k).

	Argument: i, j, k - the voxel that is currently processing;
		cfv_i, cfv_j, cfv_k - its CFV;
		cfv_val - the value of its CFV that contains the boundary face information.

*/
double distToClosetFacePointOfCFV(
				float *sp2,
				int i, int j, int k,
                                int cfv_i, int cfv_j, int cfv_k,
                                uchar cfv_val);

/*
	distToFacePoint: sub-function of distToClosetFacePointOfCFV. 

	For each boundary face, there are nine points of interests in total. This function
	determins the closet point of interests.
*/
double distToFacePoint(int unchanged,
			float *sp2,
                        double i, double j, double k,
                        double cfv_i, double cfv_j, double cfv_k);

/*
	calcDist: euclidean distance between voxel with coordinate of (i, j, k) and
	voxel with coordinate of (target_i, target_j, target_k).	
*/
double calcDist(
		float *sp2,
		double i, double j, double k,
                double target_i, double target_j, double target_k);

/*
	isKthBitSet: it helps to detect which boundary face the CFV has. 
*/
bool isKthBitSet(int n, int k);

#endif

